### PR TITLE
PI-195 Get projects from API

### PR DESCRIPTION
**Pull request by utainwitedsonthi**
PI-194 and PI-195 get API and show all pin on map.

image

### CODE REVIEW

**Review by RatreeOchn — COMMENTED** [review]
Look good for me

**Comment by rassokhin-s** [comment]
I would wait with this one until we implement endpoint which will:
1) Return public projects without token requirement.
2) Will return coordinates for projects.

**Review by rassokhin-s — CHANGES_REQUESTED** [review]
@utainwitedsonthi any progress on this task?
The endpoint is ready and you already know about it
https://api.rfcx.org/public/projects?include_location=true

**Comment by antonyharfield** [comment]
I think this is out-of-date. The latest code is all merged to `release/map-features`.

**Pull request closed without merging**
